<?php

namespace Tp\FdjBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Tp\FdjBundle\Entity\Fdj;
use Doctrine\ORM\Query;
/**
 * FdjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FdjRepository extends EntityRepository
{
    
}
